first capstone project - creating web page based on another web page creative commons
PRATAP-KUMAR/first-capstone-project pull request #1
Opened 2022-07-29 06:22 UTC by PRATAP-KUMAR

This is my first capstone project.

the challenge is to build a web page based on CreativeCommons web page that is responsive for both desktop and mobile versions.

2022-07-29 10:22 UTC, Sahar-AbdelSamad requested changes
## CHANGES REQUIRED ♻️ ♻️

Hi @PRATAP-KUMAR , :wave::wave:

You've done a great job so far :partying_face: :clap: 
However, there are some issues that you still need to work on to go to the next project but you are almost there :smile: 
![image](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Highlights
✔️ Your Project is really really awesome
✔️ You applied JavaScript best practices
✔️ You used GitHub Pages to deploy web pages

## Required Changes ♻️
- [ ] You've done a very good job so far 😍 however there is still the [About page](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) that is missing,
Here are some screenshots of it 👇
![Screenshot from 2022-07-29 13-13-55](https://user-images.githubusercontent.com/87965534/181738768-f9bdcaad-dfbd-4511-9a82-6fe5b8f720e9.png)

![Screenshot from 2022-07-29 13-14-10](https://user-images.githubusercontent.com/87965534/181738758-9c3bcd1f-79ba-4f6d-9cb1-e77a6d34008e.png)
![Screenshot from 2022-07-29 13-14-43](https://user-images.githubusercontent.com/87965534/181738747-54f07a3a-d110-4ad9-b5b9-837b3903f725.png)
Please add it ✨ you got this 💪 
 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 10:22 UTC, Sahar-AbdelSamad commented on README.md
> +- [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/)
- [ ] Please give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/) you can do that in the `Acknowledgements` or `Credits` section. 
- [ ] You can remove the 
```
Prerequisites
Setup
Install
Usage
Run tests
```
From the README since they are empty and it is more professional 😃

2022-07-29 10:22 UTC, Sahar-AbdelSamad commented on styles/header.css
> +@media only screen and (max-width: 768px) {
- [ ] The CSS styling of this project should be built as a mobile-first.
Please fix it, media queries are supposed to be used in this project to change the design from mobile to desktop, not the other way around.

2022-07-29 10:22 UTC, Sahar-AbdelSamad commented on styles/home.css
> +@media only screen and (max-width: 768px) {
- [ ] Same here, the CSS styling of this project should be built as a mobile-first.
Please fix it, media queries are supposed to be used in this project to change the design from mobile to desktop, not the other way around.

2022-07-29 10:22 UTC, Sahar-AbdelSamad commented on styles/speakers.css
> +@media only screen and (max-width: 768px) {
- [ ] Same here, the CSS styling of this project should be built as a mobile-first.
Please fix it, media queries are supposed to be used in this project to change the design from mobile to desktop, not the other way around.

2022-07-30 05:42 UTC, Ismailco requested changes
#### Hi @PRATAP-KUMAR, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![giphy](https://user-images.githubusercontent.com/25227022/169399289-510de072-42e7-419b-8c2c-da9344bdd430.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-30 05:42 UTC, Ismailco commented on index.html
> +			</div>
- [ ] As the previous reviewer mentioned you don't have an about page, kindly move your about page code to a new file, you can name it 'about.html' and add a top bar. nav bar, and footer there

![Screenshot_20220730_064108](https://user-images.githubusercontent.com/25227022/181876534-4f08568c-32c4-4669-a73d-922925583bcc.png)

2022-07-30 07:26 UTC, vickymarz approved these changes
Hi @PRATAP-KUMAR , 

# 🟢  Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 07:46 UTC, merged